import { type AppType } from "next/app";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { api } from "@/utils/api";

import "@/styles/globals.css";
import LoginBar from "@/components/LoginBar";
import Head from "next/head";
import { AdminCheckProvider } from "@/hooks/admin";
import { useState } from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});
const MyApp: AppType = ({ Component, pageProps }) => {
  const [navLoaded, setNavLoaded] = useState(false);

  return (
    <>
      <Head>
        <title>Editorial Version for TLSetsu</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClerkProvider {...pageProps}>
        <AdminCheckProvider>
          <LoginBar setLoaded={setNavLoaded} />
          {navLoaded ? (
            <main className={`font-sans ${inter.variable}`}>
              <Component {...pageProps} />
            </main>
          ) : (
            <></>
          )}
        </AdminCheckProvider>
      </ClerkProvider>
    </>
  );
};

export default api.withTRPC(MyApp);
