import Head from "next/head";
import { useRedirect } from "@/hooks/login";
import { api } from "@/utils/api";
import { TLList } from "@/components/TLList";
import { ScraperList } from "@/components/ScraperList";
import { NovelStoreProvider } from "@/hooks/novelStore";

export default function Dashboard() {
  useRedirect(true);
  console.log("redrawing list");
  const tls = api.db.getFromDB.useQuery();
  return (
    <>
      <Head>
        <title>List of TLs in Version for TLSetsu</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid w-full grid-cols-2 text-white">
        <div>{tls.data ? <TLList tls={tls.data} /> : <>Loading</>}</div>
        <div>
          <ScraperList />
        </div>
      </div>
    </>
  );
}
