import Head from "next/head";

import { useState } from "react";
import Login from "@/components/Login";
import { Dashboard } from "@/components/Dashboard/Dashboard";

export default function Home() {
  const [user, setUser] = useState<string | null>(null);

  return (
    <>
      <Head>
        <title>Editorial Version for TLSetsu</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login user={user} setUser={setUser} />
      {user && <>
        <Dashboard /> 
      </>}
    </>
  );
}
