import Head from "next/head";
import Login from "@/components/Login";
import { useRedirect, useUser } from "@/hooks/login";

export default function Home() {
  const { user, setUser } = useUser();
  useRedirect(false);

  return (
    <>
      <Head>
        <title>Editorial Version for TLSetsu</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login user={user} setUser={setUser} />
    </>
  );
}
